# Generated by Django 4.1.7 on 2023-03-12 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlableEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('crawling_status', models.IntegerField(choices=[(0, 'Not crawled'), (1, 'Error requesting link'), (2, 'Updating link'), (3, 'Marked as duplicate'), (4, 'Updated link'), (5, 'Crawling'), (6, 'Crawling failed'), (7, 'Rescheduled long crawling'), (8, 'Crawling too long'), (9, 'Has no pages'), (10, 'Text uploaded'), (11, 'Awaiting crawl'), (12, 'Indexed by elastic'), (13, 'Text analyzed'), (14, 'Domain invalid'), (15, 'No links in page'), (16, 'Uncrawlable')])),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('last_crawled', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('crawlableentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.crawlableentity')),
                ('employees_min', models.IntegerField()),
                ('employees_max', models.IntegerField()),
            ],
            bases=('api.crawlableentity',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('crawlableentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.crawlableentity')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
            ],
            bases=('api.crawlableentity',),
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('crawlableentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.crawlableentity')),
                ('start_date', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('language', models.CharField(default='en', max_length=2)),
            ],
            bases=('api.crawlableentity',),
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('crawlableentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.crawlableentity')),
                ('snippet', models.CharField(blank=True, max_length=500, null=True)),
                ('company_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='api.company')),
            ],
            bases=('api.crawlableentity',),
        ),
        migrations.CreateModel(
            name='CompanyForWebinar',
            fields=[
                ('crawlableentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.crawlableentity')),
                ('company_webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar', to='api.webinar')),
            ],
            bases=('api.crawlableentity',),
        ),
        migrations.CreateModel(
            name='CompanyForEvent',
            fields=[
                ('crawlableentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.crawlableentity')),
                ('company_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.event')),
            ],
            bases=('api.crawlableentity',),
        ),
    ]
