# Generated by Django 4.1.7 on 2023-03-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlableentity',
            name='crawling_status',
            field=models.IntegerField(choices=[(0, 'Not crawled'), (1, 'Error requesting link'), (2, 'Updating link'), (3, 'Marked as duplicate'), (4, 'Updated link'), (5, 'Crawling'), (6, 'Crawling failed'), (7, 'Rescheduled long crawling'), (8, 'Crawling too long'), (9, 'Has no pages'), (10, 'Text uploaded'), (11, 'Awaiting crawl'), (12, 'Indexed by elastic'), (13, 'Text analyzed'), (14, 'Domain invalid'), (15, 'No links in page'), (16, 'Uncrawlable')], null=True),
        ),
        migrations.AlterField(
            model_name='crawlableentity',
            name='is_blacklisted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='crawlableentity',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='crawlableentity',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crawlableentity',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
