# Generated by Django 4.1.7 on 2023-03-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_crawlableentity_crawling_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyforevent',
            name='company_event',
        ),
        migrations.RemoveField(
            model_name='companyforwebinar',
            name='company_webinar',
        ),
        migrations.AddField(
            model_name='companyforevent',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.company'),
        ),
        migrations.AddField(
            model_name='companyforevent',
            name='event_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_name', to='api.event'),
        ),
        migrations.AddField(
            model_name='companyforwebinar',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to='api.company'),
        ),
        migrations.AddField(
            model_name='companyforwebinar',
            name='webinar_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webinar_name', to='api.webinar'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employees_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='employees_min',
            field=models.IntegerField(null=True),
        ),
    ]
